### ISSUE TITLE
Vulnerability of random module

### ISSUE THREAD

**Issue by Rakesh8086** [abhinav4367/Password-Manager-Using-Python#1]
Hey Abhinav!! I went through your code and found that you have used random module for generating passwords. But it is not considered to be safe in industry standards due to its cryptographically insecure nature. If you would like, I can contribute to your project and do my bit in generating cryptographically secure passwords for your password manager.

**Comment by abhinav4367** [comment]
Hi Rakesh Teja,

Thanks for taking the time to review the code! I appreciate your concern
regarding the use of the random module for password generation. You're
absolutely right, and I value the importance of implementing
industry-standard security practices.

I would be more than happy to collaborate with you on enhancing the
security of the password manager. Your expertise in generating
cryptographically secure passwords would be a valuable addition to the
project. Feel free to share your suggestions and any code improvements you
have in mind. Collaboration is key to building robust and secure software,
and I look forward to working together on this. Thanks again for your input!

**Comment by Rakesh8086** [comment]
Thanks for the quick reply. I will work on the issue I mentioned and then give you a pull request. You can see if it matches the requirements of your project.

**Comment by abhinav4367** [comment]
Hi Rakesh8086,

I wanted to express my sincere appreciation for your recent pull request – your dedication and effort have not gone unnoticed. 🙌

I've reviewed the changes you implemented, and everything looks good! Your contribution adds significant value to the project, and I'm thrilled to see the positive impact it will have.

Thank you for taking the time to enhance our codebase and improve the overall quality of our project. Your attention to detail and commitment to excellence truly make a difference.

 I'll go ahead and merge your pull request.

Once again, thank you for your valuable contribution. Looking forward to more collaboration in the future!

Best regards.
